import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'
import { getPages } from '@/sanity/sanity-utils'
import page from '@/sanity/schemas/page-schema'
import Logo from '../../assets/logo.svg'
import Image from 'next/image'
import ResponsiveAppBar from './appbar'
import backgroundImg from '../../assets/background.jpg'
import AppbarTest from './appbarTest'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next sanity app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // get pages
  const pages=await getPages()

  return (
    <html lang="en">
      <body className="bg-[url('https://res.cloudinary.com/ai4bharat/image/upload/v1686120078/Ai4bharat-Website/Ai4bharat_Website_background_pqq0oe.jpg')] bg-no-repeat bg-center bg-cover">

        
        <div className='mx-0'>
          <header>
            {/* <ResponsiveAppBar/> */}
            <AppbarTest/>
          </header>
          <main>{children}</main>
          <footer><Footer/></footer>
        </div>
      </body>
    </html>
  )
}

